#!/usr/bin/env bash
#
# bootstrap installs things.

# Require bash
if [ -z "$BASH_VERSION" ]; then
    echo "Error: ibmi-dotfiles requires bash. Please run this script with bash." >&2
    exit 1
fi

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

set -e

install_path=${HOME};
cmd=`basename "$0"`

print_use () {
    echo "Use: ${cmd} [--install-path <path>]"
    echo "e.g.: ${cmd} --install-path /home/username"
    exit 1
}

while [[ $# -gt 0 ]]
do
    key="${1}"
    case ${key} in
    -i|--install-path)
        install_path="${2}"
        shift # past argument
        shift # past value
        ;;
    -h|--help)
        print_use
        shift # past argument
        ;;
    *)    # unknown option
        shift # past argument
        ;;
    esac
done

echo ''

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

install_gitconfig () {
    config_source="${DOTFILES_ROOT}/git/gitconfig.symlink"
    info 'setup gitconfig'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" \
    $config_source > $1

    success "copied $config_source to $1"
}

copy_files () {
    cp -r $1 $2
    success "copied $1 to $2"
}

install_dotfiles () {
    info 'installing dotfiles'

    overwrite_all=false
    backup_all=false
    skip_all=false

    local find_cmd="find"
    [[ -x /QOpenSys/pkgs/bin/find ]] && find_cmd="/QOpenSys/pkgs/bin/find"

    for source in `$find_cmd ${DOTFILES_ROOT} -maxdepth 2 -name \*.symlink*`
    do
        dest_file=".`basename \"${source%.*}\"`"
        dest="${install_path}/${dest_file}"

        if [[ -f ${dest} ]] || [[ -d ${dest} ]]
        then

            overwrite=false
            backup=false
            skip=false

            if [[ "$overwrite_all" == "false" ]] && [[ "$backup_all" == "false" ]] && [[ "$skip_all" == "false" ]]
            then
                user "File already exists: `basename ${source}`, what do you want to do?
                [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -n 1 action

                case "$action" in
                    o )
                    overwrite=true;;
                    O )
                    overwrite_all=true;;
                    b )
                    backup=true;;
                    B )
                    backup_all=true;;
                    s )
                    skip=true;;
                    S )
                    skip_all=true;;
                    * )
                    ;;
                esac
            fi

            if [[ "$overwrite" == "true" ]] || [[ "$overwrite_all" == "true" ]]
            then
                rm -rf ${dest}
                success "removed ${dest}"
            fi

            if [[ "$backup" == "true" ]] || [[ "$backup_all" == "true" ]]
            then
                mv ${dest} ${dest}\.backup
                success "moved ${dest} to ${dest}.backup"
            fi

            if [[ "$skip" == "false" ]] && [[ "$skip_all" == "false" ]]
            then
            if [[ "$dest_file" == ".gitconfig" ]]
                then
                    install_gitconfig ${dest}
                else
                    copy_files ${source} ${dest}
                fi
            else
                success "skipped ${source}"
            fi

        else
            if [[ "$dest_file" == ".gitconfig" ]]
            then
                install_gitconfig ${dest}
            else
                copy_files ${source} ${dest}
            fi
        fi

    done
}

download_git_scripts () {
    local curl_cmd
    if [[ -x /QOpenSys/pkgs/bin/curl ]]; then
        curl_cmd="/QOpenSys/pkgs/bin/curl"
    elif command -v curl &>/dev/null; then
        curl_cmd="curl"
    else
        fail "curl is required but not found. Install it with: yum install curl"
    fi

    local dest_dir="${DOTFILES_ROOT}/dotfiles.symlink"
    local git_completion_url="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    local git_prompt_url="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"

    if [[ ! -f "${dest_dir}/git-completion.bash" ]]; then
        info "downloading git-completion.bash\n"
        $curl_cmd -fsSL "$git_completion_url" -o "${dest_dir}/git-completion.bash" \
            && success "downloaded git-completion.bash" \
            || fail "failed to download git-completion.bash"
    else
        success "git-completion.bash already exists, skipping download"
    fi

    if [[ ! -f "${dest_dir}/git-prompt.sh" ]]; then
        info "downloading git-prompt.sh\n"
        $curl_cmd -fsSL "$git_prompt_url" -o "${dest_dir}/git-prompt.sh" \
            && success "downloaded git-prompt.sh" \
            || fail "failed to download git-prompt.sh"
    else
        success "git-prompt.sh already exists, skipping download"
    fi
}

download_git_scripts
install_dotfiles

echo ''
echo '  All installed!'
